# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  profitapi:
    image: profitapi
    build:
      context: .
      dockerfile: ProFit.API/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 7131:7131
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:c:\remote_debugger:rw
